### ISSUE TITLE
Correctly ejabberd MUC configuration

### ISSUE THREAD

**Issue by sattellite** [siacs/Conversations#1165]
In window of chatting with buddy in menu after click "invite contact" and selecting contact created new MUC with random name. "Conversations" app automatically opening this MUC-room. That looks good. But:
1. ejabberd sees this room is empty
2. Contact after answer to invitation cannot connect to room because this MUC-room was not been created.

For successfully invitation:
1. Open other client with same JID (Gajim in my case).
2. Invite third contact to chat with Conversations.
3.  In Gajim I have invitation to my JID to new room. Accept it.
3.1. Connecting to new room as owner (in Gajim)
3.2 In Conversations nothing changes
4. After that other recipients can accept invitation and connect to new MUC-room. 

I assume that I have not properly configured the XMPP server Ejabberd(version 15.03).
It seems to me that this method of invitation is not an implementation of [XEP-0045/continue](http://xmpp.org/extensions/xep-0045.html#continue).

This is my muc config:

```yaml
  mod_muc: 
    access: muc
    access_create: muc
    access_persistent: muc
    access_admin: muc_admin
    history_size: 50
    max_users: 500
    default_room_options:
      allow_change_subj: true
      allow_private_messages: false
      allow_user_invites: true
      logging: true
      members_by_default: true
      persistent: false
      public: true
      public_list: false
```

Can anyone show me correctly ejabberd configuration for MUC?
