### ISSUE TITLE
can't upload files with http_mod

### ISSUE THREAD

**Issue by v10star** [siacs/Conversations#1932]
#### General information

* **Version:** 1.13.3
* **Device:**LG G4 / motorola moto E / G
* **Android Version:** Android 6.0 Stock 
* **Server name:** self hosted ubuntu 16.04, all ejabberd stuff from repo, contrib included
* **Server software:** ejabberd 16.01 
* **Installed server modules:** Stream Managment, MAM on mysql, Mod_http_upload
* **Conversations source:** F-Droid

#### Steps to reproduce

1. when i try to share a file/image from my mobile client with conversation to another client logged to same server, i've got an error. below error from ejabberd log.
2. the strange thing is that from the same phone with frozenchat (fork from an old version of conversation) application logged to the same server and gajim, the transfer works.

#### Expected result

below log from ejabberd.

2016-06-27 07:52:23.449 [error] <0.9800.0>@mod_http_upload:process:418 Cannot store file /home/xmpp/upload/2ae5142b3eb324c88477aa5a7283230292067a20/of90r6PcM7x4VF3ifmpzWXNAXZhnn1aEy9T9GT6Y/hqdefault-1.jpg from 192.168.82.127 for im.bsquad.net: "no such file or directory

Server side should be fine because i haven't this error on different clients and i have no more parameters to try to change.

**Comment by iNPUTmice** [comment]
Frozenchat was forked at a time where HTTP Upload didn't even existed.

I think this ```Cannot store file /home/xmpp/upload/2ae5142b3eb324c88477aa5a7283230292067a20/of90r6PcM7x4VF3ifmpzWXNAXZhnn1aEy9T9GT6Y/hqdefault-1.jpg from 192.168.82.127 for im.bsquad.net: "no such file or directory``` is actually a pretty clear error message. Make sure the path exits.

**Comment by v10star** [comment]
yep, i've made just working now (strange thing with other client but who cares) 
i've modify my ejabberd http_upload configuration with this:

 mod_http_upload:
    docroot: "**@HOME@/upload**" previous was the absolute path reported previously that really exists
     put_url: "https://@HOST@:5443"
    thumbnail: false
    max_size: infinity
    access: local
  mod_http_upload_quota:
    max_days: infinity
    access_soft_quota: soft_upload_quota

**Comment by mkeedlinger** [comment]
Hi, I am currently having this problem. Here's my config:
```
  - 
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/files": mod_http_upload
      ##  "/pub/archive": mod_http_fileserver
    web_admin: true
    http_bind: true
    register: false
    captcha: false
    tls: true # we'll have nginx handle that
    certfile: "/etc/ejabberd/ejabberd.pem"

modules: 
  mod_http_upload:
    access: all
    thumbnail: false
    file_mode: "0640"
    dir_mode: "0755"
    docroot: "/data/ejabberd/http"
    put_url: "https://@HOST@:443/files"
```

And here's the error that `ejabberd` is giving me:

```
2018-02-12 22:10:28.408 [error] <0.493.0>@mod_http_upload:process:418 Cannot store file /data/ejabberd/http/1d677f05259fb88b2c1bf1be75f5da25c41a5d72/FYOlgcG77fy6igW46muHkADsSeUb1QKDL0unE076/IMG_20180208_142430_098.jpg from ::FFFF:127.0.0.1 for example.host: "no such file or directory"
```
Note: I switched my domain to `example.host`. I don't want this domain public.

I have `ejabberd` version `16.01-2` from the Ubuntu 16.04 repos.

Any advice?

Thanks a ton!
