### ISSUE TITLE
Http upload not available if a subdomain differing from the default value is specified in ejabberd

### ISSUE THREAD

**Issue by Flunkyball** [siacs/Conversations#3280]
#### General information

* **Version:** 2.3.6+fcr
* **Device:** Samsung Galaxy S7
* **Android Version:** LineageOS 14.1 (Android 7.1.2)
* **Server name:** self hosted
* **Server software:** ejabberd 18.06 
* **Installed server modules:** mod_http_upload
* **Conversations source:**  F-Droid

#### Steps to reproduce

1. Configure in ejabberd.yml for mod_http_upload the "host:" option with a different value than default (host: upload.domain.com), e.g. "host: ul.domain.com"
2. Restart ejabberd

#### Expected result

Http upload works with the given host name or subdomain. 

#### Actual result

Http upload is shown as not available within Conversations server info.
Http upload does not work.
Switching back to the default vaule "upload.@HOST@" does solve the issue even though the subdomain does not exist.

**Comment by licaon-kter** [comment]
Attach whole config, both port and module.

**Comment by Flunkyball** [comment]
Here we go....

Port config:
```
    ## XEP-0363, HTTP File Upload
  -
    port: 5443
    module: ejabberd_http
    tls: true
    dhfile: "/etc/ejabberd/dhparams.pem"
    tls_compression: false
    ciphers: "HIGH:!MEDIUM:!LOW:!3DES:!CAMELLIA:!aNULL:!RSA@STRENGTH"
    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "cipher_server_preference"
    request_handlers:
      "upload": mod_http_upload
```
Module Config:
```

  ## XEP-0363, HTTP File Upload

  mod_http_upload:
    host: "ul.@HOST@"
    docroot: "/var/ejabberd-http-upload/"
    put_url: "https://ul.domain.com/files"
```
