### ISSUE TITLE
Incompatible Server

### ISSUE THREAD

**Issue by chathudan** [siacs/Conversations#893]
I'm using ejabberd server , I can connect using other xmpp client but I can not use same credentials with Conversations. It gave Incompatible Server error

**Comment by jkufner** [comment]
I'm using ejabberd 14.07 from Debian packages with no trouble.

Have you checked ejabberd logs for errors or warnings ?


Chathura Wijesinghe wrote, on 16.1.2015 21:38:

**Comment by SamWhited** [comment]
You probably don't have TLS turned on. This is an issue tracker though, not a support forums. Can you join the conference room (`conversations@conference.siacs.eu`) and we can try to debug there?

**Comment by chathudan** [comment]
I have disable TLS on code level too , @jkufner what are the configuration on ejabberd.yml ? I'll join the conference room

**Comment by jkufner** [comment]
Chathura Wijesinghe wrote, on 16.1.2015 22:03:
what are the configuration on ejabberd.yml?

Nothing special. Mostly default configuration, a bunch of transports
(spectrum) and few virtual hosts, each with its own certificate (all on
single IP address).

```
listen:
  -
    port: 5222
    module: ejabberd_c2s
    certfile: "/etc/ssl/example.com.cert+priv+sub.key"
    starttls: true
    starttls_required: true
    #max_stanza_size: 65536
    max_ack_queue: 32767
    resume_timeout: 1200        # 20 minutes to recover session,
    resend_on_timeout: true     # but it is okay to timeout.
    shaper: c2s_shaper
    access: c2s

host_config:
  "example.com":
    domain_certfile: "/etc/ssl/example.com.cert+priv+sub.key"
  "example.org":
    domain_certfile: "/etc/ssl/example.org.cert+priv+sub.key"
  "example.net":
    domain_certfile: "/etc/ssl/example.net.cert+priv+sub.key"

```
